### PR TITLE
#39 Migrate the Ecore GLSP Server build to P2

### LINKED ISSUE #39: Migrate the Ecore GLSP Server build to P2
Initially, the GLSP Server artifacts were provided via Maven. However, they are now provided through both Maven and P2, with P2 being the primary source (Containing all nightlies).

The Ecore GLSP Server still relies on M2, which makes it harder to follow GLSP Server updates. It's time to migrate! :)

### PR DESCRIPTION
**Pull request by CamilleLetavernier**
- Update the server build to use P2/Tycho rather than plain Maven
- Fix a version inconsistency between GLSP Client and GLSP Server, that caused issues with Ecore Edges

fixes #39

### CODE REVIEW

**Comment by CamilleLetavernier** [comment]
The plug-in approach doesn't work with Maven Shade; I'll need to find a different approach. It's currently used to package the Ecore GLSP Server in an all-in-one jar, that can then be started directly from the Client Backend (So it's used to avoid having to start the server manually).

When developing from Eclipse, it's not an issue, as we resolve all dependencies through PDE, but for a deployed runtime, we need a different solution. We might provide an Eclipse product (Like we already do for the Ecore Model backend), or maybe we can make Maven Shade work with plug-ins. 

@tortmayr @planger @simongraband What do you think?

**Comment by CamilleLetavernier** [comment]
In the meantime, I'll split the PR in two: one for updating GLSP with the current build (Plain Maven), and one follow-up for the migration to P2

**Comment by tortmayr** [comment]
We currently use maven-shade only in plain maven builds. If you have a p2 build the recommended solution is to provide a headless eclipse product. As you mentioned you already do this for the ecore model backend, so adapting the approach for the glsp server should not be an issue.

**Comment by CamilleLetavernier** [comment]
> If you have a p2 build the recommended solution is to provide a headless eclipse product

:+1:

**Comment by CamilleLetavernier** [comment]
I've updated the PR:

- It has been rebased on top of master, which includes #42 / #43 (So the PR now only focuses on the P2/Eclipse Product migration)

The new PR:

- Update the server build to use P2/Tycho rather than plain Maven
- Copy the Maven artifacts to client/theia-ecore/build (2 products: one for "Ecore Backend" and one for "Ecore GLSP")
- The Theia Backend Extensions have been updated to start the Product/Applications rather than all-in-one jars

**Pull request merged**
